AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: compare-yourself-app

Resources:
  cyStoreDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/cy-store-data.cyStoreDataHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /compare-yourself
            Method: POST

