AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: compare-yourself-app

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: compare-yourself
      StageName: dev
      Description: Allows users to compare themselves

