AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: compare-yourself-app

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: "'POST"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: "'true'"
  cyStoreDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/cy-store-data.cyStoreDataHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /compare-yourself
            Method: POST
            RestApiId:
              Ref: ApiGatewayApi

