name: Deploy

on:
    workflow_dispatch:

env:
    AWS_REGION: us-east-1
    STACK_NAME: compare-yourself-app

jobs:
    deploy-dev:
        name: Deploy to Development
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Setup SAM CLI
              uses: aws-actions/setup-sam@v2

            - name: Build SAM application
              run: sam build

            - name: Deploy
              run: |
                sam deploy --stack-name ${{env.STACK_NAME}} \
                --template-file .aws-sam/build/template.yaml \
                --capabilities CAPABILITY_IAM \
                --no-fail-on-empty-changeset \

        
