name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
    AWS_REGION: us-east-1
    STACK_NAME: compare-yourself-app
    SAM_CLI_VERSION: 1.131.0

jobs:
    deploy-dev:
        name: Deploy to Development
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache SAM CLI
              id: cache-sam
              uses: actions/cache@v3
              with:
                path: |
                  ~/.aws-sam
                  ~/.sam
                key: sam-cli-${{ runner.os }}-${{ env.SAM_CLI_VERSION }}

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Setup SAM CLI
              uses: aws-actions/setup-sam@v2
              with:
                version: ${{ env.SAM_CLI_VERSION }}
              if: steps.cache-sam.outputs.cache-hit != 'true'

            - name: Build SAM application
              run: sam build

            - name: Package SAM application
              run: sam package

            - name: Deploy
              run: sam deploy

        
